#-------------------------------
# General Site Settings

title: SO4
description: SO4 is powered by Jekyll and Github Pages
email: so4gangshit@gmail.com

menu:
- {name: 'Music', url: ''}
- {name: 'Shows', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'SO4 MUSIC'
  rel-author: 'https://plus.google.com/u/0/112676606207303422744'
  rel-publisher: 'https://plus.google.com/u/0/112676606207303422744'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >
  # SO4
  [CHEFBOI RD](https://soundcloud.com/david-ochieng)
  
  [Kan$han The Scholar](https://soundcloud.com/kantaro-horino7)
  [Fuji Kyle](https://soundcloud.com/fuji-kyle)
  [Tubby T](https://soundcloud.com/prodbytubbyt)
  


contact: >
  # Contact

  You can contact us [through email](mailto:so4gangshit@gmail.com) or [twitter](https://twitter.com/intent/tweet?text=%4so4_gang) for collaborations and inquiries 

#-------------------------------
# Work Section

projects:
- {name: 'STAY BROKE', folder: 'proj-1', file: 'projects/proj-1.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/so4_gang'}
- {icon: 'instagram', link: 'https://www.instagram.com/so4_gang/?hl=en'}
- {icon: 'envelope', link: 'mailto:so4gangshit@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
