#-------------------------------
# General Site Settings

title: SO4
description: SO4 is powered by Jekyll and Github Pages
email: so4gangshit@gmail.com

menu:
- {name: 'Music', url: ''}
- {name: 'Shows', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'SO4 MUSIC'
  rel-author: 'https://plus.google.com/u/0/112676606207303422744'
  rel-publisher: 'https://plus.google.com/u/0/112676606207303422744'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >

  [_CHEFBOI RD_](https://soundcloud.com/david-ochieng)       ***       [_Kan$han The Scholar_](https://soundcloud.com/kantaro-horino7)
  
  
  ![CHEFBOI RD](https://github.com/so4gang/so4gang.github.io/blob/master/assets/img/avatar/chefboird.jpg?raw=true) ![Kan$han The Scholar](https://github.com/so4gang/so4gang.github.io/blob/master/assets/img/avatar/kanshan.jpg?raw=true)
    


  [_Fuji Kyle_](https://soundcloud.com/fuji-kyle)       ***       [_Tubby T_](https://soundcloud.com/prodbytubbyt)
  
  
  ![Fuji Kyle](https://github.com/so4gang/so4gang.github.io/blob/master/assets/img/avatar/fujikyle.jpg?raw=true) ![Tubby T](https://github.com/so4gang/so4gang.github.io/blob/master/assets/img/avatar/tubbyt.jpg?raw=true)

  

  [_youn Xeno_](https://soundcloud.com/kingxeno)
  
  
  ![youn Xeno](https://github.com/so4gang/so4gang.github.io/blob/master/assets/img/avatar/xeno.jpg?raw=true)



contact: >
  # Contact

  You can contact us [through email](mailto:so4gangshit@gmail.com) or [instagram](https://www.instagram.com/officialso4) for collaborations and inquiries 

#-------------------------------
# Work Section

projects:
- {name: 'GROOVE', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Wild Thoughts', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'VIBES', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'GAS', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Gas REMIX', folder: 'proj-5', file: 'projects/proj-5.html'}
- {name: 'FACADE', folder: 'proj-6', file: 'projects/proj-6.html'}
- {name: 'ImTheFuckingScholar', folder: 'proj-7', file: 'projects/proj-7.html'}
- {name: 'Everything Was Meant', folder: 'proj-8', file: 'projects/proj-8.html'}
- {name: 'Smoking Dope', folder: 'proj-9', file: 'projects/proj-9.html'}
- {name: 'Higher', folder: 'proj-10', file: 'projects/proj-10.html'}
- {name: 'Higher', folder: 'proj-11', file: 'projects/proj-11.html'}









#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://www.instagram.com/officialso4'}
- {icon: 'envelope', link: 'mailto:so4gangshit@gmail.com'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCmYS_Fu9PBQoEeZgb7de_Xw?view_as=subscriber'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/user-454793257'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
